name: ar_indoor_navigation
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.2.0
  firebase_auth: ^4.1.2
  firebase_storage: ^11.0.6
  cloud_firestore: ^4.0.5
  dropdown_button2: ^1.8.9
  get: ^4.6.5
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^0.22.0
  intl: ^0.17.0
  simple_animations: ^5.0.0+3
  uuid: ^3.0.7
  image_picker: ^0.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - lib/icons/
